### ISSUE TITLE
Testing Feedback: Account Profile Image Size Limit

### ISSUE THREAD

**Issue by NigelLu** [gcivil-nyu-org/Wednesday-Fall2023-Team-6#190]
Hi Team 6,

I've been testing your application and it is outstanding. However, I do have a small suggestion to make. For instance, I uploaded a JPG file of size 21MB, and got this response (screenshot below). 

I am not sure if this is a constraint enforced by AWS's nginx server before the request even reaching your application. If yes, I think there is little you can do except for adding frontend JS to check for file size before POST. If no, then when uploading the user profile image file, you probably want to add another constraint on the file size a user is allowed to POST. This could make your already great application even more robust.

<img width="1199" alt="Screenshot 2023-11-16 at 14 55 08" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/52246554/83d2edaf-7eca-4695-b2b7-01c2f5bb6274">

Hope this is helpful and feel free to comment under this issue should you have any question.

**Comment by Chinnu1103** [comment]
Hi @NigelLu thanks so much for testing our application, appreciate it!!
Regarding the issue you reported, we are aware of it and have included this as part of the 'Scenarios NOT To Be Tested' section of the Test Party document (you can find it on the last page, second last point).
You're correct, its the limitation of the AWS server,  and we are planning to either add a check or some type of compression algorithm in the future to handle this issue.

**Comment by Chinnu1103** [comment]
For now, I'm transferring this to the icebox pipeline.

**Comment by NigelLu** [comment]
> For now, I'm transferring this to the icebox pipeline.

Oh got it. Sorry for not reading carefully enough through the testing doc.

**Comment by Chinnu1103** [comment]
> > For now, I'm transferring this to the icebox pipeline.
> 
> Oh got it. Sorry for not reading carefully enough through the testing doc.

No worries ✌️, who reads the whole thing anyway lol
