### ISSUE TITLE
Testing Party: Lacking phone number validation when booking an appointment

### ISSUE THREAD

**Issue by WenjunYuAnny** [gcivil-nyu-org/Wednesday-Fall2023-Team-6#193]
Your website looks definitely impressive!
I noticed one small thing: when booking an appointment, I was able to put in a phone number as "111", which is not really a reasonable phone number. I know this might be trivial, but just in case this is not on your list.
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/130470692/615d4f2b-7851-4fae-a3ee-689b8cb4969d)

**Comment by Chinnu1103** [comment]
Hi, thanks so much for reporting the issue!
We will look into this.

**Comment by Chinnu1103** [comment]
3 checks:
1. It may/may not start with a plus
2. All others should be numbers
3. Length should be between 10-13
