### ISSUE TITLE
Testing party feedback : missing validation on profile details

### ISSUE THREAD

**Issue by himanshu1196** [gcivil-nyu-org/Wednesday-Fall2023-Team-6#199]
What I did : Edited my profile's phone number and zipcode
What went wrong : I was able to add arbitrary numbers for both fields. 
Validation on these two fields should be useful to avoid any erroneous edits by mistake.
![Screenshot (111)](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/14277620/03c8c4b9-ec48-4e6a-a480-40dde76ac013)
![Screenshot (112)](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/14277620/049f3f39-a7d0-41c2-8774-37ef7d40be48)

**Comment by Chinnu1103** [comment]
Hi @himanshu1196 , thanks for checking this but this has already been reported [here](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/issues/193)
We have fixed this in our integration branch, and it should be pushed to prod after the test party.
So marking this as duplicate and closing for now.

**Comment by Chinnu1103** [comment]
Reopening since the other issue did not include zipcode check. Considering this issue as zipcode validation bug.
