### ISSUE TITLE
Testing party feedback : missing error details while booking appointments

### ISSUE THREAD

**Issue by himanshu1196** [gcivil-nyu-org/Wednesday-Fall2023-Team-6#200]
What I did : Tried to book an appointment with invalid data
What happened : presented with an error message "Validation Error. Please ensure your details are correct."
As an improvement it could be helpful to mention the specific errors which caused this failure. e.g. email is incorrect.
![Screenshot (113)](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/14277620/00ef1367-d7ac-4db2-bdf7-f5e7b8af0878)

**Comment by Chinnu1103** [comment]
Hi thanks for your suggestion!
Even though this would make the UI more intuitive, we are considering this as a feature request and not a bug.
For now, we expect the user to identify the incorrect details themselves. We may incorporate this in the future though!
