### ISSUE TITLE
Testing Party: Cannot book onsite appointment

### ISSUE THREAD

**Issue by yp2353** [gcivil-nyu-org/Wednesday-Fall2023-Team-6#202]
I thought we are able to book onsite appointment, but it keeps giving me validation error even though my information is the same as my profile

<img width="1384" alt="Screen Shot 2023-11-17 at 10 57 16 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/113962530/8a1b7602-8b97-498a-8ed5-f04ab00edb13">

**Comment by Chinnu1103** [comment]
Hi, the reason for appointment is a mandatory field. I think the asterix sign on the field is missing.
Sorry for the confusion.

**Comment by yp2353** [comment]
Oh I see!

**Comment by Chinnu1103** [comment]
For now, considering this as a bug for mandatory fields
