### ISSUE TITLE
Testing Party: Form validation

### ISSUE THREAD

**Issue by yp2353** [gcivil-nyu-org/Wednesday-Fall2023-Team-6#203]
I open a doctor's page and in another tab I open my profile. In the doctor's page, you have form validation which throws error if my information is incorrect (ie form info does not match my profile). However, if in my other tab I edit and change my profile info, the doctor page's form is still checking for my old info, instead of the new one I just changed to.

<img width="1492" alt="Screen Shot 2023-11-17 at 11 04 52 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-6/assets/113962530/8d9e3b2a-9474-4080-b95e-4d85656b5ee7">

**Comment by Chinnu1103** [comment]
Hi @yp2353 thanks for testing our app!
The form validation does not check if your profile information matches the book consultation information. 
The form details could be for any patient (who may not even be on the app) that you are booking on behalf of.
Hence the validation for both these pages will occur separately. 
Please let me know if this has cleared your doubt.

**Comment by yp2353** [comment]
I was getting validation error, but I now see it's just checking for the email which cannot be changed. Looks good!
